
- name: Add Elasticsearch GPG Key
  block:
    - name: elasticsearch-install | Import Elasticsearch GPG Key
      ansible.builtin.shell: "curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor > /usr/share/keyrings/elasticsearch-keyring.gpg"

    - name: Add Elasticsearch APT Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: "elastic-8.x.list"

    - name: Install logstash package
      ansible.builtin.apt:
        name: logstash
        state: present

- name: Fetch file from elk-master
  ansible.builtin.fetch:
    src: /etc/elasticsearch/certs/http_ca.crt
    dest: /tmp/
    flat: yes
  delegate_to: elk1

- name: Ensure target directory for certificates exists
  ansible.builtin.file:
    path: /etc/logstash/certs
    state: directory
    owner: logstash
    group: logstash
    mode: '0755'
    
- name: Copy file from elk-master to logstash
  ansible.builtin.copy:
    src: /tmp/http_ca.crt
    dest: /etc/logstash/certs/http_ca.crt
    owner: logstash
    group: logstash
    mode: '0644'

- name: Copy Logstash Output Configuration
  ansible.builtin.template:
    src: templates/elasticsearch-output.conf.j2
    dest: /etc/logstash/conf.d/elasticsearch-output.conf
    mode: 0640
    owner: logstash
    group: logstash

- name: Enable and Start Logstash Service
  service:
    name: logstash
    state: started
    enabled: yes

- name: Show Logstash logs
  shell: journalctl -u logstash -n 50 --no-pager
  register: logstash_logs

- name: Display Logstash logs
  debug:
    var: logstash_logs.stdout