---
- name: Install required packages for RHEL
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - gpgme
    - curl
    - procps-ng
    - net-tools
    - gnupg2


- name: Add Elasticsearch GPG Key and YUM Repository
  block:
    - name: Import Elasticsearch GPG Key
      ansible.builtin.shell: "curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor > /etc/pki/rpm-gpg/elasticsearch-keyring.gpg"

    - name: Add Elasticsearch YUM Repository
      ansible.builtin.yum_repository:
        name: elasticsearch
        description: "Elasticsearch repository for 8.x packages"
        baseurl: "https://artifacts.elastic.co/packages/8.x/yum"
        gpgcheck: yes
        gpgkey: "file:///etc/pki/rpm-gpg/elasticsearch-keyring.gpg"
        enabled: yes

    - name: Install Elasticsearch package
      ansible.builtin.dnf:
        name: elasticsearch
        state: present

- name: Check if Elasticsearch node is already part of the cluster
  shell: curl --silent --cacert /etc/elasticsearch/certs/http_ca.crt -u elastic:{{ hostvars['elk-master']['elastic_password'] }} https://{{ ansible_host }}:9200/_cat/nodes?h=name
  register: existing_nodes
  failed_when: false
  changed_when: false

- name: Run elasticsearch-reconfigure-node with the enrollment token (if not in cluster)
  shell: test -f /etc/elasticsearch/reconfigure_done || /usr/share/elasticsearch/bin/elasticsearch-reconfigure-node --enrollment-token {{ hostvars['elk-master']['enrollment_token'] }}
  args:
    stdin: "y\n"
  register: reconfigure_output
  changed_when: reconfigure_output.rc == 0
  when: "'{{ inventory_hostname }}' not in existing_nodes.stdout"

- name: Create reconfigure_done marker file
  file:
    path: /etc/elasticsearch/reconfigure_done
    state: touch
  when: reconfigure_output is changed

- name: Enable and start Elasticsearch service
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Use curl to test Elasticsearch connection
  shell: curl --silent --cacert /etc/elasticsearch/certs/http_ca.crt -u elastic:{{ hostvars['elk-master']['elastic_password'] }} https://{{ ansible_host }}:9200/_cluster/health?pretty
  register: curl_response

- name: Display curl response
  ansible.builtin.debug:
    msg: "{{ curl_response.stdout }}"
