---
- name: Install required packages
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
    update_cache: yes

- name: Add Elasticsearch GPG Key
  block:
    - name: Import Elasticsearch GPG Key
      ansible.builtin.shell: "curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor > /etc/pki/rpm-gpg/elasticsearch-keyring.gpg"

    - name: Add Elasticsearch YUM Repository
      ansible.builtin.yum_repository:
        name: elasticsearch
        description: "Elasticsearch repository for 8.x packages"
        baseurl: "https://artifacts.elastic.co/packages/8.x/yum"
        gpgcheck: yes
        gpgkey: "file:///etc/pki/rpm-gpg/elasticsearch-keyring.gpg"
        enabled: yes

    - name: Install Kibana package
      ansible.builtin.dnf:
        name: kibana
        state: present

- name: Run Kibana Enrollment Token Command
  shell: /usr/share/kibana/bin/kibana-setup --enrollment-token {{ hostvars['elk1']['kibana_enrollment_token'] }}
  args:
    stdin: "y\n"

- name: Ensure elasticsearch.hosts is updated
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#?elasticsearch\.hosts:.*$'
    line: "elasticsearch.hosts: [\"{{ elastic_hosts | replace(',', '\", \"') }}\"]"
    backrefs: yes
  tags: deneme

- name: Enable and Start Kibana Service
  service:
    name: kibana
    state: started
    enabled: yes
