- name: Import Kibana GPG Key
  ansible.builtin.shell: "rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch"

- name: Add Kibana YUM Repository using blockinfile
  ansible.builtin.blockinfile:
    path: /etc/yum.repos.d/kibana.repo
    block: |
      [kibana-8.x]
      name=Kibana repository for 8.x packages
      baseurl=https://artifacts.elastic.co/packages/8.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md
    create: yes
    owner: root
    group: root
    mode: '0644'

- name: Install Kibana package
  ansible.builtin.yum:
    name: kibana
    state: present

- name: Run Kibana Enrollment Token Command
  shell: /usr/share/kibana/bin/kibana-setup --enrollment-token {{ hostvars['elk1']['kibana_enrollment_token'] }}
  args:
    stdin: "y\n"

- name: Ensure elasticsearch.hosts is updated
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#?elasticsearch\.hosts:.*$'
    line: "elasticsearch.hosts: [\"{{ elastic_hosts | replace(',', '\", \"') }}\"]"
    backrefs: yes


- name: Enable and Start Kibana Service
  service:
    name: kibana
    state: started
    enabled: yes
