- hosts: elk-master
  become: true
  gather_facts: true
  roles:
    - elasticsearch-master
  
- hosts: elk-node
  become: true
  gather_facts: true
  roles:
    - elasticsearch-node
  environment: 
    DEBIAN_FRONTEND: noninteractive