- hosts: elk-master
  become: true
  gather_facts: true
  roles:
    - elasticsearch-master
  
- hosts: elk-node
  become: true
  gather_facts: true
  roles:
    - elasticsearch-node
  environment: 
    DEBIAN_FRONTEND: noninteractive

- hosts: elk-all
  become: true
  gather_facts: true
  roles:
    - elk-post-process
  serial: 1
  environment: 
    DEBIAN_FRONTEND: noninteractive

- hosts: kibana
  become: true
  gather_facts: true
  roles:
    - kibana

- hosts: dev_downstream_rke2_master
  gather_facts: true
  become: true
  roles:
    - filebeat

- hosts: elk-all:kibana
  gather_facts: true
  become: true
  roles:
    - elk-final-check
