- name: Install parted package
  package:
    name: parted
    state: present

- name: Create a primary partition on /dev/nvme1n1
  community.general.parted:
    device: "{{ vm_disk_path }}"
    number: 1
    part_type: primary
    state: present
    part_start: 0%
    part_end: 100%

- name: Wait for udev to process the new partition
  command: udevadm settle

- name: Format the partition with ext4 filesystem
  filesystem:
    fstype: ext4
    dev: /dev/nvme1n1p1

- name: Create mount point directory
  file:
    path: /mnt
    state: directory
    mode: '0755'

- name: Mount the partition
  mount:
    path: /mnt
    src: /dev/nvme1n1p1
    fstype: ext4
    opts: defaults
    state: mounted

- name: Ensure the partition is mounted on boot
  mount:
    path: /mnt
    src: /dev/nvme1n1p1
    fstype: ext4
    opts: defaults
    state: present
    
