# TODO: add documentation

- name: Write to Consul KV
  ansible.builtin.uri:
    url: "{{ consul_uri }}"
    method: PUT
    headers:
      X-Consul-Token: "{{ consul_token }}"
    status_code: "{{ status_code }}"
    body_format: json
    body: "{{ request_body | to_nice_json}}"
  register: _write_consul_response # static name
  debugger: on_failed
  # failed_when: "false == _write_consul_response.changed"

# TODO: failed_when 


- name: Set Fact - Write Consul response dynamically to "{{ register_to }}"
  ansible.builtin.set_fact:
    "{{ register_to }}": "{{ _write_consul_response }}"
  when: register_to is defined

