---
- name: Ensure Kibana service is running on the Kibana host
  ansible.builtin.service_facts:
  when: inventory_hostname == "kibana"

- name: Check if Kibana service is running
  debug:
    msg: "Kibana service is running"
  when: 
    - inventory_hostname == "kibana"
    - ansible_facts.services['kibana.service'].state == 'running'

- name: Check if Kibana service is not running
  debug:
    msg: "Kibana service is not running"
  when: 
    - inventory_hostname == "kibana"
    - ansible_facts.services['kibana.service'].state != 'running'

- name: Ensure Logstash service is running on the Logstash host
  ansible.builtin.service_facts:
  when: inventory_hostname == "logstash"

- name: Check if Logstash service is running
  debug:
    msg: "Logstash service is running"
  when: 
    - inventory_hostname == "logstash"
    - ansible_facts.services['logstash.service'].state == 'running'

- name: Check if Logstash service is not running
  debug:
    msg: "Logstash service is not running"
  when: 
    - inventory_hostname == "logstash"
    - ansible_facts.services['logstash.service'].state != 'running'

- name: Ensure Elasticsearch service is running on Elasticsearch hosts
  ansible.builtin.service_facts:
  when: inventory_hostname in groups['elk-all']

- name: Check if Elasticsearch service is running
  debug:
    msg: "Elasticsearch service is running"
  when: 
    - inventory_hostname in groups['elk-all']
    - ansible_facts.services['elasticsearch.service'].state == 'running'

- name: Check if Elasticsearch service is not running
  debug:
    msg: "Elasticsearch service is not running"
  when: 
    - inventory_hostname in groups['elk-all']
    - ansible_facts.services['elasticsearch.service'].state != 'running'

- name: Use curl to test Elasticsearch connection
  shell: curl --cacert /etc/elasticsearch/certs/http_ca.crt -u elastic:{{ hostvars['elk1']['elastic_password'] }} https://{{ ansible_host }}:9200/_cluster/health?pretty
  register: curl_response_final
  when: inventory_hostname in groups['elk-all']

- name: Display curl response
  debug:
    msg: "{{ curl_response_final.stdout }}"
  when: inventory_hostname in groups['elk-all']

