- name: Update apt cache
  apt: update_cache=yes

- name: ensure nginx is at the latest version
  apt:
    name: nginx
    state: latest
    
- name: start nginx
  service: 
    name: nginx
    state: started
    enabled: yes 