# TODO: add documentation

- name: Read a kv2 secret
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_address }}"
    path: "{{ secret_path }}"
    auth_method: token
    token: "{{ vault_token }}"
  register: _vault_kv2_read_result # static name
  debugger: on_failed

- name: Set Fact - Vault KV2 secret read result dynamically to "{{ register_to }}"
  ansible.builtin.set_fact:
    "{{ register_to }}": "{{ _vault_kv2_read_result }}"
  when: register_to is defined